name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore vcpkg dependencies
      run: vcpkg install --triplet x64-windows

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DAUTO_DOWNLOAD_FFMPEG=ON

    - name: Build
      run: cmake --build build --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenReplay
        path: build/OpenReplay/Release/
